#!/bin/bash
set -e

# Set debug mode
set -x
set -v

# Setup environment variables.
export CMAKE_ADDITIONAL_OPTIONS=" ${CMAKE_ADDITIONAL_OPTIONS} -DBUILD_UNIT_TESTS=\"ON\""

# Setup environment variables.
. ./.travis/run ../.travis/build

# End debug mode
set +v
set +x
