#!/bin/bash
set -e

# Set debug mode
set -x
set -v

# Add robotpkg
sudo sh -c "echo \"deb http://robotpkg.openrobots.org/packages/debian precise robotpkg\" >> /etc/apt/sources.list "
curl http://robotpkg.openrobots.org/packages/debian/robotpkg.key | sudo apt-key add -
#sudo apt-get update

# show memory usage before install
sudo free -m -t

# Setup environment variables.

# Add dependencies from apt
export APT_DEPENDENCIES="doxygen doxygen-latex libboost-all-dev libeigen3-dev liblapack-dev libblas-dev gfortran"
# Add dependencies from robot-pkg
export APT_DEPENDENCIES=$APT_DEPENDENCIES" robotpkg-pinocchio robotpkg-jrl-mal+jrl-mathtools"

# Add one git dependency
export GIT_DEPENDENCIES=$GIT_DEPENDENCIES" https://github.com/laas/simple_humanoid.git"

# Set the distribution to be precise
export DIST=""

# When this script is called the current directory is ./custom_travis
. ./.travis/run ../.travis/before_install

# End debug mode
set +v
set +x
