jrl-walkgen: OptimalControllerSolver.cpp File Reference
OptimalControllerSolver.cpp File Reference
#include <iostream>
#include <PreviewControl/OptimalControllerSolver.hh>
#include <Debug.hh>
Typedefs
typedef long int logical
typedef double doublereal
typedef logical(* L_fp)(...)
typedef int integer
Functions
doublereal dlapy2_ (doublereal *, doublereal *)
double dlamch_ (char *)
int dgges_ (char *, char *, char *, L_fp, integer *, doublereal *, integer *, doublereal *, integer *, integer *, doublereal *, doublereal *, doublereal *, doublereal *, integer *, doublereal *, integer *, doublereal *, integer *, logical *, integer *)
logical sb02ox (double *_alphar, double *_alphai, double *_beta)
logical sb02ow (double *_alphar, double *, double *_beta)
Typedef Documentation
typedef double doublereal
typedef int integer
typedef logical(* L_fp)(...)
typedef long int logical
Function Documentation
int dgges_ (char * , char * , char * , L_fp , integer * , doublereal * , integer * , doublereal * , integer * , integer * , doublereal * , doublereal * , doublereal * , doublereal * , integer * , doublereal * , integer * , doublereal * , integer * , logical * , integer *)
Referenced by PatternGeneratorJRL::OptimalControllerSolver::GeneralizedSchur().
double dlamch_ (char *)
Referenced by sb02ow().
doublereal dlapy2_ (doublereal * , doublereal *)
Referenced by sb02ox().
logical sb02ow (double * _alphar, double * , double * _beta)
References dlamch_().
logical sb02ox (double * _alphar, double * _alphai, double * _beta)
References dlapy2_(), and w.
Referenced by PatternGeneratorJRL::OptimalControllerSolver::GeneralizedSchur().