jrl-walkgen: PatternGeneratorJRL::RelativeFeetInequalities Class Reference
PatternGeneratorJRL::RelativeFeetInequalities Class Reference
Generate a stack of inequalities relative to feet centers for the whole preview window.
#include </home/buildbot/devel-src/tools/pkg-dev-mng/Testing/Buildbot/slaves/jrlserver/jrlserverubuntu/build-jrl-walkgen-jrlmt-master/pkgsrc/src/Mathematics/relative-feet-inequalities.hh>
Classes
struct edges_s
Public Member Functions
int setVertices (convex_hull_t &ConvexHull, double Orientation, const support_state_t &SupportState, int constraints_type)
Adapt vertices to the support foot and its orientation.
int computeLinearSystem (const convex_hull_t &ConvexHull, MAL_MATRIX(&D, double), MAL_MATRIX(&Dc, double), const support_state_t &PrwSupport) const
Compute the linear inequalities associated with the convex hull specified by a vector of points.
int computeLinearSystem (const convex_hull_t &ConvexHull, double *D_x, double *D_y, double *d, const support_state_t &PrwSupport) const
Compute the linear inequalities associated with the convex hull specified by a vector of points.
virtual void CallMethod (std::string &Method, std::istringstream &Args)
Reimplement the interface of SimplePluginManager.
Constructors and destructors.
RelativeFeetInequalities (SimplePluginManager *aSPM, CjrlHumanoidDynamicRobot *aHS)
~RelativeFeetInequalities ()
Static Public Attributes
static const int ZMP_CONSTRAINTS = 0
static const int FOOT_CONSTRAINTS = 1
Detailed Description
Generate a stack of inequalities relative to feet centers for the whole preview window.
Constructor & Destructor Documentation
RelativeFeetInequalities::RelativeFeetInequalities (SimplePluginManager * aSPM, CjrlHumanoidDynamicRobot * aHS)
RelativeFeetInequalities::~RelativeFeetInequalities ()
Member Function Documentation
void RelativeFeetInequalities::CallMethod (std::string & Method, std::istringstream & Args) [virtual]
Reimplement the interface of SimplePluginManager.
Parameters:
[in] Method,: The method to be called.
[in] Args,: Arguments of the methods.
References PatternGeneratorJRL::FootHalfSize::setConstraints().
int RelativeFeetInequalities::computeLinearSystem (const convex_hull_t & ConvexHull, double * D_x, double * D_y, double * d, const support_state_t & PrwSupport) const
Compute the linear inequalities associated with the convex hull specified by a vector of points.
Parameters:
[in] aVecOfPoints a vector of vertices
[out] D_x left hand side of the constraints
[out] D_y left hand side of the constraints
[out] Dc right hand side of the constraints
[in] PrwSupport previewed support state
Returns:
0
int RelativeFeetInequalities::computeLinearSystem (const convex_hull_t & ConvexHull, MAL_MATRIX &, double, MAL_MATRIX &, double, const support_state_t & PrwSupport) const
Compute the linear inequalities associated with the convex hull specified by a vector of points.
Parameters:
[in] aVecOfPoints a vector of vertices
[out] D left hand side of the inequalities
[out] Dc right hand side of the inequalities
[in] PrwSupport previewed support state
Returns:
0
References MAL_MATRIX, MAL_MATRIX_RESIZE, and n.
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_inequalities_cop(), and PatternGeneratorJRL::GeneratorVelRef::build_inequalities_feet().
int RelativeFeetInequalities::setVertices (convex_hull_t & ConvexHull, double Orientation, const support_state_t & SupportState, int constraints_type)
Adapt vertices to the support foot and its orientation.
Parameters:
[out] ConvexHull vertices of the ZMP convex hull
[in] Orientation
[in] SupportState
[in] constraints_type
Returns:
0
References FOOT_CONSTRAINTS, and ZMP_CONSTRAINTS.
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_inequalities_cop(), and PatternGeneratorJRL::GeneratorVelRef::build_inequalities_feet().
Member Data Documentation
const int PatternGeneratorJRL::RelativeFeetInequalities::FOOT_CONSTRAINTS = 1 [static]
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_inequalities_feet(), and setVertices().
const int PatternGeneratorJRL::RelativeFeetInequalities::ZMP_CONSTRAINTS = 0 [static]
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_inequalities_cop(), and setVertices().