PatternGeneratorJRL Namespace Reference
PatternGeneratorJRL Namespace Reference
Classes
class PatternGeneratorInterface
This class is the interface between the Pattern Generator and the external world.
struct COMPosition_s
Structure to store the COM position computed by the preview control.
struct COMState_s
Structure to store the COM state computed by the preview control.
struct RelativeFootPosition_s
Structure to store each foot position when the user is specifying a sequence of relative positions.
struct ZMPPosition_s
Structure to store each of the ZMP value, with a given direction at a certain time.
struct FootAbsolutePosition_t
Structure to store the absolute foot position.
struct LinearConstraintInequality_s
struct LinearConstraintInequalityFreeFeet_s
Linear constraints with variable feet placement.
struct SupportFeet_s
struct ReferenceAbsoluteVelocity_t
Structure to store the absolute reference.
class AnalyticalZMPCOGTrajectory
struct ltCH_Point
struct CH_Point
class ComputeConvexHull
class FootConstraintsAsLinearSystem
class FootConstraintsAsLinearSystemForVelRef
class FootHalfSize
class Polynome
Class for computing trajectories.
class Polynome3
Polynome used for X,Y and Theta trajectories.
class Polynome4
Polynome used for Z trajectory.
class Polynome5
Polynome used for X,Y and Theta trajectories.
class Polynome6
Polynome used for Z trajectory.
class StepOverPolynomeFoot
Polynome used for Z trajectory during stepover.
class StepOverPolynomeFootZtoX
Polynome used for Z trajectory during stepover.
class StepOverPolynomeFootXtoTime
Polynome used for X trajectory in function of time to combine with StepOverPolynomeFootZtoX.
class StepOverPolynomeHip4
Polynome for the hip trajectory.
class StepOverSpline
spline function calculation class to calculate cubic splines
class StepOverClampedCubicSpline
class LinearizedInvertedPendulum2D
class OptimalControllerSolver
This class computes the gains for preview control for a given discrete system. The discrete system is defined by three matrix A, b, c such as :
.
class PreviewControl
Class to implement the preview control.
class SupportFSM
class ZMPPreviewControlWithMultiBodyZMP
Object to generate the angle positions every 5 ms from a set of absolute foot positions.
Typedefs
typedef struct COMPosition_s COMPosition
typedef struct COMPosition_s WaistState
typedef struct COMState_s COMState
typedef struct
RelativeFootPosition_s RelativeFootPosition
typedef struct ZMPPosition_s ZMPPosition
typedef struct
FootAbsolutePosition_t FootAbsolutePosition
typedef struct
LinearConstraintInequality_s LinearConstraintInequality_t
typedef struct
LinearConstraintInequalityFreeFeet_s LinearConstraintInequalityFreeFeet_t
typedef struct SupportFeet_s SupportFeet_t
typedef struct
ReferenceAbsoluteVelocity_t ReferenceAbsoluteVelocity
typedef std::vector< CH_Point > ConvexHullList
Functions
WALK_GEN_JRL_EXPORT
PatternGeneratorInterface * patternGeneratorInterfaceFactory (CjrlHumanoidDynamicRobot *aHDR)
ostream & operator<< (ostream &os, const AnalyticalZMPCOGTrajectory &obj)
void DistanceCHRep (CH_Point &s1, CH_Point &s2, double &distance1, double &distance2)
double CompareCBRep (CH_Point &s1, CH_Point &s2)
Variables
CH_Point HRP2CIO_GlobalP0
Detailed Description
STL includes
Framework includes
Typedef Documentation
typedef struct COMPosition_s PatternGeneratorJRL::COMPosition
typedef struct COMState_s PatternGeneratorJRL::COMState
typedef std::vector<CH_Point> PatternGeneratorJRL::ConvexHullList
typedef struct FootAbsolutePosition_t PatternGeneratorJRL::FootAbsolutePosition
typedef struct LinearConstraintInequality_s PatternGeneratorJRL::LinearConstraintInequality_t
typedef struct LinearConstraintInequalityFreeFeet_s PatternGeneratorJRL::LinearConstraintInequalityFreeFeet_t
typedef struct ReferenceAbsoluteVelocity_t PatternGeneratorJRL::ReferenceAbsoluteVelocity
typedef struct RelativeFootPosition_s PatternGeneratorJRL::RelativeFootPosition
typedef struct SupportFeet_s PatternGeneratorJRL::SupportFeet_t
typedef struct COMPosition_s PatternGeneratorJRL::WaistState
typedef struct ZMPPosition_s PatternGeneratorJRL::ZMPPosition
Function Documentation
double PatternGeneratorJRL::CompareCBRep (CH_Point & s1, CH_Point & s2)
References PatternGeneratorJRL::CH_Point::col, HRP2CIO_GlobalP0, and PatternGeneratorJRL::CH_Point::row.
Referenced by PatternGeneratorJRL::ComputeConvexHull::DoComputeConvexHull().
void PatternGeneratorJRL::DistanceCHRep (CH_Point & s1, CH_Point & s2, double & distance1, double & distance2)
References PatternGeneratorJRL::CH_Point::col, HRP2CIO_GlobalP0, and PatternGeneratorJRL::CH_Point::row.
Referenced by PatternGeneratorJRL::ComputeConvexHull::DoComputeConvexHull().
std::ostream & PatternGeneratorJRL::operator<< (ostream & os, const AnalyticalZMPCOGTrajectory & obj)
References PatternGeneratorJRL::Polynome::GetCoefficients(), PatternGeneratorJRL::AnalyticalZMPCOGTrajectory::GetFromListOfCOGPolynomials(), PatternGeneratorJRL::AnalyticalZMPCOGTrajectory::GetFromListOfZMPPolynomials(), PatternGeneratorJRL::AnalyticalZMPCOGTrajectory::GetHyperbolicCoefficients(), PatternGeneratorJRL::AnalyticalZMPCOGTrajectory::GetNumberOfIntervals(), and PatternGeneratorJRL::AnalyticalZMPCOGTrajectory::GetPolynomialDegrees().
WALK_GEN_JRL_EXPORT PatternGeneratorInterface* PatternGeneratorJRL::patternGeneratorInterfaceFactory (CjrlHumanoidDynamicRobot * aHDR)
Factory of Pattern generator interface.
Variable Documentation
CH_Point PatternGeneratorJRL::HRP2CIO_GlobalP0
Referenced by CompareCBRep(), DistanceCHRep(), PatternGeneratorJRL::ComputeConvexHull::DoComputeConvexHull(), and PatternGeneratorJRL::ltCH_Point::operator()().