jrl-walkgen: PatternGeneratorJRL::IntermedQPMat Class Reference
PatternGeneratorJRL::IntermedQPMat Class Reference
Custom (value based) container providing intermediate elements for the construction of a QP.
#include </home/buildbot/devel-src/tools/pkg-dev-mng/Testing/Buildbot/slaves/jrlserver/jrlserverubuntu/build-jrl-walkgen-jrlmt-master/pkgsrc/src/Mathematics/intermediate-qp-matrices.hh>
Classes
struct dynamics_s
struct objective_variant_s
struct state_variant_s
Public Types
Matrices defining the evolution
typedef dynamics_s dynamics_t
QP elements that are objective independent
typedef state_variant_s state_variant_t
Least square objective's dependent elements
typedef objective_variant_s objective_variant_t
Public Member Functions
Constructors and destructors.
IntermedQPMat ()
~IntermedQPMat ()
Accessors
Getter and setter
state_variant_t const & State () const
state_variant_t & State ()
objective_variant_t const & Objective (int type) const
objective_variant_t & Objective (int type)
dynamics_t const & Dynamics (int type) const
dynamics_t & Dynamics (int type)
linear_inequality_t const & Inequalities (int type) const
linear_inequality_t & Inequalities (int type)
com_t const & CoM () const
void CoM (const com_t &CoM)
reference_t const & Reference () const
reference_t & Reference ()
void Reference (const reference_t &Ref)
support_state_t const & SupportState () const
support_state_t & SupportState ()
void SupportState (const support_state_t &SupportState)
Displaying
Dump objective matrices
void dumpObjective (const int ObjectiveType, std::ostream &aos)
void dumpState (std::ostream &aos)
void dumpObjective (const char *filename, const int Objectivetype)
void dumpState (const char *filename)
Static Public Attributes
static const int MEAN_VELOCITY = 0
static const int INSTANT_VELOCITY = 1
static const int COP_CENTERING = 2
static const int JERK_MIN = 3
static const int POSITION = 10
static const int VELOCITY = 11
static const int ACCELERATION = 12
static const int JERK = 13
static const int COP = 14
static const int INEQ_COP = 20
static const int INEQ_COM = 21
static const int INEQ_FEET = 22
Detailed Description
Custom (value based) container providing intermediate elements for the construction of a QP.
Member Typedef Documentation
typedef dynamics_s PatternGeneratorJRL::IntermedQPMat::dynamics_t
typedef objective_variant_s PatternGeneratorJRL::IntermedQPMat::objective_variant_t
typedef state_variant_s PatternGeneratorJRL::IntermedQPMat::state_variant_t
Constructor & Destructor Documentation
IntermedQPMat::IntermedQPMat ()
References ACCELERATION, COP, COP_CENTERING, PatternGeneratorJRL::IntermedQPMat::objective_variant_s::dyn, INEQ_COM, INEQ_COP, INEQ_FEET, INSTANT_VELOCITY, JERK, JERK_MIN, MEAN_VELOCITY, POSITION, PatternGeneratorJRL::IntermedQPMat::dynamics_s::type, PatternGeneratorJRL::IntermedQPMat::objective_variant_s::type, and VELOCITY.
IntermedQPMat::~IntermedQPMat ()
Member Function Documentation
void PatternGeneratorJRL::IntermedQPMat::CoM (const com_t & CoM) [inline]
References PatternGeneratorJRL::IntermedQPMat::state_variant_s::CoM.
com_t const& PatternGeneratorJRL::IntermedQPMat::CoM () const [inline]
References PatternGeneratorJRL::IntermedQPMat::state_variant_s::CoM.
Referenced by PatternGeneratorJRL::GeneratorVelRef::CoM().
void IntermedQPMat::dumpObjective (const char * filename, const int Objectivetype)
References dumpObjective().
void IntermedQPMat::dumpObjective (const int ObjectiveType, std::ostream & aos)
References COP_CENTERING, INSTANT_VELOCITY, JERK_MIN, and PatternGeneratorJRL::IntermedQPMat::objective_variant_s::print().
Referenced by dumpObjective().
void IntermedQPMat::dumpState (const char * filename)
References dumpState().
void IntermedQPMat::dumpState (std::ostream & aos)
Referenced by dumpState().
IntermedQPMat::dynamics_t & IntermedQPMat::Dynamics (int type)
Default behavior return velocity.
References COP, JERK, and VELOCITY.
IntermedQPMat::dynamics_t const & IntermedQPMat::Dynamics (int type) const
References COP, JERK, and VELOCITY.
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_constraints(), and PatternGeneratorJRL::GeneratorVelRef::initialize_matrices().
linear_inequality_t & IntermedQPMat::Inequalities (int type)
References INEQ_COM, INEQ_COP, and INEQ_FEET.
linear_inequality_t const & IntermedQPMat::Inequalities (int type) const
References INEQ_COM, INEQ_COP, and INEQ_FEET.
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_constraints(), and PatternGeneratorJRL::GeneratorVelRef::initialize_matrices().
IntermedQPMat::objective_variant_t & IntermedQPMat::Objective (int type)
References COP_CENTERING, INSTANT_VELOCITY, JERK_MIN, and MEAN_VELOCITY.
IntermedQPMat::objective_variant_t const & IntermedQPMat::Objective (int type) const
References COP_CENTERING, INSTANT_VELOCITY, JERK_MIN, and MEAN_VELOCITY.
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_invariant_part(), PatternGeneratorJRL::GeneratorVelRef::Ponderation(), and PatternGeneratorJRL::GeneratorVelRef::update_problem().
void PatternGeneratorJRL::IntermedQPMat::Reference (const reference_t & Ref) [inline]
References PatternGeneratorJRL::IntermedQPMat::state_variant_s::Ref.
reference_t& PatternGeneratorJRL::IntermedQPMat::Reference () [inline]
References PatternGeneratorJRL::IntermedQPMat::state_variant_s::Ref.
reference_t const& PatternGeneratorJRL::IntermedQPMat::Reference () const [inline]
References PatternGeneratorJRL::IntermedQPMat::state_variant_s::Ref.
Referenced by PatternGeneratorJRL::GeneratorVelRef::compute_global_reference(), PatternGeneratorJRL::GeneratorVelRef::preview_support_states(), and PatternGeneratorJRL::GeneratorVelRef::Reference().
state_variant_t& PatternGeneratorJRL::IntermedQPMat::State () [inline]
state_variant_t const& PatternGeneratorJRL::IntermedQPMat::State () const [inline]
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_constraints(), PatternGeneratorJRL::GeneratorVelRef::generate_selection_matrices(), and PatternGeneratorJRL::GeneratorVelRef::update_problem().
void PatternGeneratorJRL::IntermedQPMat::SupportState (const support_state_t & SupportState) [inline]
References PatternGeneratorJRL::IntermedQPMat::state_variant_s::SupportState.
support_state_t& PatternGeneratorJRL::IntermedQPMat::SupportState () [inline]
References PatternGeneratorJRL::IntermedQPMat::state_variant_s::SupportState.
support_state_t const& PatternGeneratorJRL::IntermedQPMat::SupportState () const [inline]
References PatternGeneratorJRL::IntermedQPMat::state_variant_s::SupportState.
Referenced by PatternGeneratorJRL::GeneratorVelRef::GeneratorVelRef(), PatternGeneratorJRL::GeneratorVelRef::preview_support_states(), and PatternGeneratorJRL::GeneratorVelRef::SupportState().
Member Data Documentation
const int PatternGeneratorJRL::IntermedQPMat::ACCELERATION = 12 [static]
Referenced by IntermedQPMat().
const int PatternGeneratorJRL::IntermedQPMat::COP = 14 [static]
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_constraints(), Dynamics(), PatternGeneratorJRL::GeneratorVelRef::initialize_matrices(), and IntermedQPMat().
const int PatternGeneratorJRL::IntermedQPMat::COP_CENTERING = 2 [static]
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_invariant_part(), dumpObjective(), IntermedQPMat(), Objective(), and PatternGeneratorJRL::GeneratorVelRef::update_problem().
const int PatternGeneratorJRL::IntermedQPMat::INEQ_COM = 21 [static]
Referenced by Inequalities(), and IntermedQPMat().
const int PatternGeneratorJRL::IntermedQPMat::INEQ_COP = 20 [static]
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_constraints(), Inequalities(), PatternGeneratorJRL::GeneratorVelRef::initialize_matrices(), and IntermedQPMat().
const int PatternGeneratorJRL::IntermedQPMat::INEQ_FEET = 22 [static]
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_constraints(), Inequalities(), and IntermedQPMat().
const int PatternGeneratorJRL::IntermedQPMat::INSTANT_VELOCITY = 1 [static]
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_invariant_part(), dumpObjective(), IntermedQPMat(), Objective(), and PatternGeneratorJRL::GeneratorVelRef::update_problem().
const int PatternGeneratorJRL::IntermedQPMat::JERK = 13 [static]
Referenced by Dynamics(), PatternGeneratorJRL::GeneratorVelRef::initialize_matrices(), and IntermedQPMat().
const int PatternGeneratorJRL::IntermedQPMat::JERK_MIN = 3 [static]
Referenced by PatternGeneratorJRL::GeneratorVelRef::build_invariant_part(), dumpObjective(), IntermedQPMat(), and Objective().
const int PatternGeneratorJRL::IntermedQPMat::MEAN_VELOCITY = 0 [static]
Referenced by IntermedQPMat(), and Objective().
const int PatternGeneratorJRL::IntermedQPMat::POSITION = 10 [static]
Referenced by IntermedQPMat().
const int PatternGeneratorJRL::IntermedQPMat::VELOCITY = 11 [static]
Referenced by Dynamics(), PatternGeneratorJRL::GeneratorVelRef::initialize_matrices(), and IntermedQPMat().