jrl-walkgen: PatternGeneratorJRL::FootHalfSize Class Reference
PatternGeneratorJRL::FootHalfSize Class Reference
#include </home/buildbot/devel-src/tools/pkg-dev-mng/Testing/Buildbot/slaves/jrlserver/jrlserverubuntu/build-jrl-walkgen-jrlmt-master/pkgsrc/src/Mathematics/FootHalfSize.hh>
Public Member Functions
FootHalfSize ()
~FootHalfSize ()
void setHalfSizeInit (double lHalfWidth, double lHalfHeight)
void setConstraints (double OnX, double OnY)
double getHalfHeight () const
double getHalfWidth () const
double getHalfHeightDS () const
Protected Member Functions
void updateHalfHeightDS ()
void updateHalfSize ()
Detailed Description
This class handles the size and the constraints related to the feet
Constructor & Destructor Documentation
FootHalfSize::FootHalfSize ()
FootHalfSize::~FootHalfSize ()
Member Function Documentation
double FootHalfSize::getHalfHeight () const
double FootHalfSize::getHalfHeightDS () const
double FootHalfSize::getHalfWidth () const
void FootHalfSize::setConstraints (double OnX, double OnY)
References updateHalfHeightDS(), and updateHalfSize().
Referenced by PatternGeneratorJRL::RelativeFeetInequalities::CallMethod().
void FootHalfSize::setHalfSizeInit (double lHalfWidth, double lHalfHeight)
References updateHalfHeightDS(), and updateHalfSize().
void FootHalfSize::updateHalfHeightDS () [protected]
Referenced by setConstraints(), and setHalfSizeInit().
void FootHalfSize::updateHalfSize () [protected]
Referenced by setConstraints(), and setHalfSizeInit().