jrl-walkgen: PatternGeneratorJRL::QPProblem_s Struct Reference
PatternGeneratorJRL::QPProblem_s Struct Reference
Final optimization problem. This object stores and solves a quadratic problem with linear constraints.
#include </home/buildbot/devel-src/tools/pkg-dev-mng/Testing/Buildbot/slaves/jrlserver/jrlserverubuntu/build-jrl-walkgen-jrlmt-master/pkgsrc/src/ZMPRefTrajectoryGeneration/qp-problem.hh>
Classes
struct array_s
Handle matrices/vectors in array form.
struct solution_s
Solution.
Public Types
typedef struct solution_s solution_t
Public Member Functions
QPProblem_s ()
Initialize by default an empty problem.
~QPProblem_s ()
Release the memory at the end only.
void setNbVariables (int nb_variables)
Set the number of optimization parameters.
void setNbEqConstraints (int nb_eq_constraints)
Set the number of optimization parameters.
void setNbConstraints (int nb_constraints)
Set the number of optimization parameters.
template<class type >
int resize (type *&array, int old_size, int new_size)
Reallocate array.
void addTerm (const MAL_MATRIX(&Mat, double), int type, int row, int col)
Add a matrix to the final optimization problem in array form.
void addTerm (const MAL_VECTOR(&Vec, double), int type, int row)
Add a vector to the final optimization problem in array form.
void dumpProblem (const char *filename)
Dump on disk a problem.
void dump (int type, const char *filename)
Dump on disk an array.
void clear ()
Initialize set of arrays.
void clear (int type)
Initialize whole array.
void solve (int solver, solution_t &result)
Solve the problem.
Static Public Attributes
static const int MATRIX_Q = 0
static const int MATRIX_DU = 1
static const int VECTOR_D = 2
static const int VECTOR_DS = 3
static const int VECTOR_XL = 4
static const int VECTOR_XU = 5
static const int QLD = 10
static const int PLDP = 11
Protected Member Functions
void releaseMemory ()
Relese memory.
void resizeAll ()
Allocate memory.
Detailed Description
Final optimization problem. This object stores and solves a quadratic problem with linear constraints.
Member Typedef Documentation
typedef struct solution_s PatternGeneratorJRL::QPProblem_s::solution_t
Constructor & Destructor Documentation
QPProblem_s::QPProblem_s ()
Initialize by default an empty problem.
QPProblem_s::~QPProblem_s ()
Release the memory at the end only.
References releaseMemory().
Member Function Documentation
void QPProblem_s::addTerm (const MAL_VECTOR &, double, int type, int row)
Add a vector to the final optimization problem in array form.
Parameters:
Mat Added vector
ype Target vector type
row First row inside the target
References resizeAll(), VECTOR_D, VECTOR_DS, VECTOR_XL, and VECTOR_XU.
void QPProblem_s::addTerm (const MAL_MATRIX &, double, int type, int row, int col)
Add a matrix to the final optimization problem in array form.
Parameters:
Mat Added matrix
type Target matrix type
row First row inside the target
col First column inside the target
References MAL_MATRIX_NB_COLS, MAL_MATRIX_NB_ROWS, MATRIX_DU, MATRIX_Q, and resizeAll().
Referenced by PatternGeneratorJRL::GeneratorVelRef::buildConstraintsCoP(), PatternGeneratorJRL::GeneratorVelRef::buildConstraintsFeet(), PatternGeneratorJRL::GeneratorVelRef::buildInvariantPart(), and PatternGeneratorJRL::GeneratorVelRef::updateProblem().
void QPProblem_s::clear (int type)
Initialize whole array.
Parameters:
[in] type
References MATRIX_DU, MATRIX_Q, VECTOR_D, VECTOR_DS, VECTOR_XL, and VECTOR_XU.
void PatternGeneratorJRL::QPProblem_s::clear ()
Initialize set of arrays.
Referenced by PatternGeneratorJRL::GeneratorVelRef::updateProblem().
void QPProblem_s::dump (int type, const char * filename)
Dump on disk an array.
Parameters:
type
filename
void QPProblem_s::dumpProblem (const char * filename)
Dump on disk a problem.
void QPProblem_s::releaseMemory () [protected]
Relese memory.
Referenced by ~QPProblem_s().
template<class type > int PatternGeneratorJRL::QPProblem_s::resize (type *& array, int old_size, int new_size) [inline]
Reallocate array.
Parameters:
[in] array
[in] old_size
[in] new_size
void QPProblem_s::resizeAll () [protected]
Allocate memory.
Called when setting the dimensions of the problem.
Parameters:
[in] nb_variables
[in] nb_constraints
Referenced by addTerm().
void PatternGeneratorJRL::QPProblem_s::setNbConstraints (int nb_constraints) [inline]
Set the number of optimization parameters.
Parameters:
nb_constraints
void PatternGeneratorJRL::QPProblem_s::setNbEqConstraints (int nb_eq_constraints) [inline]
Set the number of optimization parameters.
Parameters:
nb_eq_constraints
void PatternGeneratorJRL::QPProblem_s::setNbVariables (int nb_variables) [inline]
Set the number of optimization parameters.
Parameters:
nb_variables
void QPProblem_s::solve (int solver, solution_t & result)
Solve the problem.
Parameters:
[in] solver
[out] result
References PatternGeneratorJRL::QPProblem_s::solution_s::Fail, PatternGeneratorJRL::QPProblem_s::solution_s::Print, ql0001_(), QLD, PatternGeneratorJRL::QPProblem_s::solution_s::resize(), PatternGeneratorJRL::QPProblem_s::solution_s::vecConstrLagr, PatternGeneratorJRL::QPProblem_s::solution_s::vecLBoundsLagr, PatternGeneratorJRL::QPProblem_s::solution_s::vecSolution, and PatternGeneratorJRL::QPProblem_s::solution_s::vecUBoundsLagr.
Member Data Documentation
const int PatternGeneratorJRL::QPProblem_s::MATRIX_DU = 1 [static]
Referenced by addTerm(), PatternGeneratorJRL::GeneratorVelRef::buildConstraintsCoP(), PatternGeneratorJRL::GeneratorVelRef::buildConstraintsFeet(), and clear().
const int PatternGeneratorJRL::QPProblem_s::MATRIX_Q = 0 [static]
Referenced by addTerm(), PatternGeneratorJRL::GeneratorVelRef::buildInvariantPart(), clear(), and PatternGeneratorJRL::GeneratorVelRef::updateProblem().
const int PatternGeneratorJRL::QPProblem_s::PLDP = 11 [static]
const int PatternGeneratorJRL::QPProblem_s::QLD = 10 [static]
Referenced by solve().
const int PatternGeneratorJRL::QPProblem_s::VECTOR_D = 2 [static]
Referenced by addTerm(), clear(), and PatternGeneratorJRL::GeneratorVelRef::updateProblem().
const int PatternGeneratorJRL::QPProblem_s::VECTOR_DS = 3 [static]
Referenced by addTerm(), PatternGeneratorJRL::GeneratorVelRef::buildConstraintsCoP(), PatternGeneratorJRL::GeneratorVelRef::buildConstraintsFeet(), and clear().
const int PatternGeneratorJRL::QPProblem_s::VECTOR_XL = 4 [static]
Referenced by addTerm(), and clear().
const int PatternGeneratorJRL::QPProblem_s::VECTOR_XU = 5 [static]
Referenced by addTerm(), and clear().