jrl-walkgen: PatternGeneratorJRL::GeneratorVelRef Class Reference
PatternGeneratorJRL::GeneratorVelRef Class Reference
Generate optimization problem as proposed in Herdt2010IROS.
#include </home/buildbot/devel-src/tools/pkg-dev-mng/Testing/Buildbot/slaves/jrlserver/jrlserverubuntu/build-jrl-walkgen-jrlmt-master/pkgsrc/src/ZMPRefTrajectoryGeneration/generator-vel-ref.hh>
Public Member Functions
void preview_support_states (const SupportFSM *FSM, std::deque< support_state_t > &deqSupportStates)
Preview support state for the whole preview period.
void compute_global_reference (const std::deque< COMState > &TrunkStates_deq)
Set the global reference from the local one and the orientation of the trunk frame for the whole preview window.
void initialize_matrices ()
Initialize intermediate matrices.
void build_constraints (QPProblem &Pb, RelativeFeetInequalities *RFI, const std::deque< FootAbsolutePosition > &AbsoluteLeftFootPositions, const std::deque< FootAbsolutePosition > &AbsoluteRightFootPositions, const std::deque< support_state_t > &deqSupportStates, const std::deque< double > &PreviewedSupportAngles)
Compute constraints.
void build_invariant_part (QPProblem &Pb)
Build the constant part of the objective.
void update_problem (QPProblem &Pb, const std::deque< support_state_t > &SupportStates_deq)
Compute the objective matrices.
void Ponderation (double weight, int objective)
Set the weights on an objective term.
Constructors and destructors.
GeneratorVelRef (SimplePluginManager *lSPM)
~GeneratorVelRef ()
void Reference (const reference_t &Ref)
Inline accessors
void SupportState (const support_state_t &SupportState)
void CoM (const com_t &CoM)
Protected Member Functions
void generate_selection_matrices (const std::deque< support_state_t > &deqSupportStates)
Compute the selection matrices.
void build_inequalities_cop (linear_inequality_t &Inequalities, RelativeFeetInequalities *FCALS, const std::deque< FootAbsolutePosition > &AbsoluteLeftFootPositions, const std::deque< FootAbsolutePosition > &AbsoluteRightFootPositions, const std::deque< support_state_t > &deqSupportStates, const std::deque< double > &PreviewedSupportAngles) const
Generate a queue of inequalities with respect to the centers of the feet.
void build_inequalities_feet (linear_inequality_t &Inequalities, RelativeFeetInequalities *FCALS, const std::deque< FootAbsolutePosition > &AbsoluteLeftFootPositions, const std::deque< FootAbsolutePosition > &AbsoluteRightFootPositions, const std::deque< support_state_t > &deqSupportStates, const std::deque< double > &PreviewedSupportAngles) const
Generate a queue of inequality constraints on the feet positions with respect to previous foot positions.
void build_constraints_cop (const linear_inequality_t &IneqCoP, const IntermedQPMat::dynamics_t &CoP, const IntermedQPMat::state_variant_t &State, int NbStepsPreviewed, QPProblem &Pb)
Compute CoP constraints corresponding to the set of inequalities.
void build_constraints_feet (const linear_inequality_t &IneqFeet, const IntermedQPMat::state_variant_t &State, int NbStepsPreviewed, QPProblem &Pb)
Compute feet constraints corresponding to the set of inequalities.
void initialize_matrices (IntermedQPMat::dynamics_t &Objective)
Initialize intermediate matrices.
void initialize_matrices (linear_inequality_t &Inequalities)
Initialize inequality matrices.
void compute_term (MAL_MATRIX(&weightMM, double), double weight, const MAL_MATRIX(&M1, double), const MAL_MATRIX(&M2, double))
Scaled product.
void compute_term (MAL_MATRIX(&MM, double), const MAL_MATRIX(&M1, double), const MAL_MATRIX(&M2, double))
Scaled product.
void compute_term (MAL_VECTOR(&weightMV, double), double weight, const MAL_MATRIX(&M, double), const MAL_VECTOR(&V, double))
Scaled product .
void compute_term (MAL_VECTOR(&weightMV, double), double weight, const MAL_MATRIX(&M, double), const MAL_VECTOR(&V, double), const double scalar)
Scaled product .
void compute_term (MAL_VECTOR(&weightMV, double), double weight, const MAL_MATRIX(&M1, double), MAL_VECTOR(&V1, double), const MAL_MATRIX(&M2, double), const MAL_VECTOR(&V2, double))
Scaled product .
Protected Attributes
IntermedQPMat Matrices_
Detailed Description
Generate optimization problem as proposed in Herdt2010IROS.
Constructor & Destructor Documentation
GeneratorVelRef::GeneratorVelRef (SimplePluginManager * lSPM)
References Matrices_, and PatternGeneratorJRL::IntermedQPMat::SupportState().
GeneratorVelRef::~GeneratorVelRef ()
Member Function Documentation
void GeneratorVelRef::build_constraints (QPProblem & Pb, RelativeFeetInequalities * RFI, const std::deque< FootAbsolutePosition > & AbsoluteLeftFootPositions, const std::deque< FootAbsolutePosition > & AbsoluteRightFootPositions, const std::deque< support_state_t > & deqSupportStates, const std::deque< double > & PreviewedSupportAngles)
Compute constraints.
Parameters:
[in] Pb
[in] FCALS
[in] AbsoluteLeftFootPositions
[in] AbsoluteRightFootPositions
[in] deqSupportStates
[in] PreviewedSupportAngles
References build_constraints_cop(), build_constraints_feet(), build_inequalities_cop(), build_inequalities_feet(), PatternGeneratorJRL::IntermedQPMat::COP, PatternGeneratorJRL::IntermedQPMat::Dynamics(), PatternGeneratorJRL::IntermedQPMat::INEQ_COP, PatternGeneratorJRL::IntermedQPMat::INEQ_FEET, PatternGeneratorJRL::IntermedQPMat::Inequalities(), Matrices_, and PatternGeneratorJRL::IntermedQPMat::State().
void GeneratorVelRef::build_constraints_cop (const linear_inequality_t & IneqCoP, const IntermedQPMat::dynamics_t & CoP, const IntermedQPMat::state_variant_t & State, int NbStepsPreviewed, QPProblem & Pb) [protected]
Compute CoP constraints corresponding to the set of inequalities.
Parameters:
[in] IneqCop
[in] CoP
[in] State
[in] NbStepsPreviewed
[in] Pb
References PatternGeneratorJRL::QPProblem_s::add_term(), PatternGeneratorJRL::IntermedQPMat::state_variant_s::CoM, compute_term(), PatternGeneratorJRL::QPProblem_s::MATRIX_DU, PatternGeneratorJRL::MPCTrajectoryGeneration::N_, PatternGeneratorJRL::IntermedQPMat::dynamics_s::S, PatternGeneratorJRL::IntermedQPMat::state_variant_s::SupportState, PatternGeneratorJRL::IntermedQPMat::dynamics_s::U, PatternGeneratorJRL::IntermedQPMat::state_variant_s::V, PatternGeneratorJRL::IntermedQPMat::state_variant_s::Vc, and PatternGeneratorJRL::QPProblem_s::VECTOR_DS.
Referenced by build_constraints().
void GeneratorVelRef::build_constraints_feet (const linear_inequality_t & IneqFeet, const IntermedQPMat::state_variant_t & State, int NbStepsPreviewed, QPProblem & Pb) [protected]
Compute feet constraints corresponding to the set of inequalities.
Parameters:
[in] IneqFeet
[in] State
[in] NbStepsPreviewed
[in] Pb
References PatternGeneratorJRL::QPProblem_s::add_term(), compute_term(), PatternGeneratorJRL::QPProblem_s::MATRIX_DU, PatternGeneratorJRL::MPCTrajectoryGeneration::N_, PatternGeneratorJRL::IntermedQPMat::state_variant_s::SupportState, PatternGeneratorJRL::IntermedQPMat::state_variant_s::V_f, PatternGeneratorJRL::IntermedQPMat::state_variant_s::Vc_f, and PatternGeneratorJRL::QPProblem_s::VECTOR_DS.
Referenced by build_constraints().
void GeneratorVelRef::build_inequalities_cop (linear_inequality_t & Inequalities, RelativeFeetInequalities * FCALS, const std::deque< FootAbsolutePosition > & AbsoluteLeftFootPositions, const std::deque< FootAbsolutePosition > & AbsoluteRightFootPositions, const std::deque< support_state_t > & deqSupportStates, const std::deque< double > & PreviewedSupportAngles) const [protected]
Generate a queue of inequalities with respect to the centers of the feet.
Parameters:
[out] Inequalities
[in] FCALS
[in] AbsoluteLeftFootPositions
[in] AbsoluteRightFootPositions
[in] deqSupportStates
[in] PreviewedSupportAngles
References PatternGeneratorJRL::RelativeFeetInequalities::computeLinearSystem(), PatternGeneratorJRL::MPCTrajectoryGeneration::N_, PatternGeneratorJRL::RelativeFeetInequalities::setVertices(), and PatternGeneratorJRL::RelativeFeetInequalities::ZMP_CONSTRAINTS.
Referenced by build_constraints().
void GeneratorVelRef::build_inequalities_feet (linear_inequality_t & Inequalities, RelativeFeetInequalities * FCALS, const std::deque< FootAbsolutePosition > & AbsoluteLeftFootPositions, const std::deque< FootAbsolutePosition > & AbsoluteRightFootPositions, const std::deque< support_state_t > & deqSupportStates, const std::deque< double > & PreviewedSupportAngles) const [protected]
Generate a queue of inequality constraints on the feet positions with respect to previous foot positions.
Parameters:
[out] Inequalities
[in] FCALS
[in] AbsoluteLeftFootPositions
[in] AbsoluteRightFootPositions
[in] deqSupportStates
[in] PreviewedSupportAngles
References PatternGeneratorJRL::RelativeFeetInequalities::computeLinearSystem(), PatternGeneratorJRL::RelativeFeetInequalities::FOOT_CONSTRAINTS, PatternGeneratorJRL::MPCTrajectoryGeneration::N_, and PatternGeneratorJRL::RelativeFeetInequalities::setVertices().
Referenced by build_constraints().
void GeneratorVelRef::build_invariant_part (QPProblem & Pb)
Build the constant part of the objective.
Parameters:
[in] Pb
References PatternGeneratorJRL::QPProblem_s::add_term(), compute_term(), PatternGeneratorJRL::IntermedQPMat::COP_CENTERING, PatternGeneratorJRL::IntermedQPMat::objective_variant_s::dyn, PatternGeneratorJRL::IntermedQPMat::INSTANT_VELOCITY, PatternGeneratorJRL::IntermedQPMat::JERK_MIN, Matrices_, PatternGeneratorJRL::QPProblem_s::MATRIX_Q, PatternGeneratorJRL::MPCTrajectoryGeneration::N_, PatternGeneratorJRL::IntermedQPMat::Objective(), and PatternGeneratorJRL::IntermedQPMat::objective_variant_s::weight.
void PatternGeneratorJRL::GeneratorVelRef::CoM (const com_t & CoM) [inline]
References PatternGeneratorJRL::IntermedQPMat::CoM(), and Matrices_.
void GeneratorVelRef::compute_global_reference (const std::deque< COMState > & TrunkStates_deq)
Set the global reference from the local one and the orientation of the trunk frame for the whole preview window.
Parameters:
[in] TrunkStateT State of the trunk at the end of the acceleration phase
References MAL_VECTOR_RESIZE, Matrices_, PatternGeneratorJRL::MPCTrajectoryGeneration::N_, PatternGeneratorJRL::IntermedQPMat::Reference(), PatternGeneratorJRL::MPCTrajectoryGeneration::T_Ctr_, and PatternGeneratorJRL::MPCTrajectoryGeneration::T_Prw_.
void GeneratorVelRef::compute_term (MAL_VECTOR &, double, double weight, const MAL_MATRIX &, double, MAL_VECTOR &, double, const MAL_MATRIX &, double, const MAL_VECTOR &, double) [protected]
Scaled product .
References MAL_RET_A_by_B.
void GeneratorVelRef::compute_term (MAL_VECTOR &, double, double weight, const MAL_MATRIX &, double, const MAL_VECTOR &, double, const double scalar) [protected]
Scaled product .
References MAL_RET_A_by_B.
void GeneratorVelRef::compute_term (MAL_VECTOR &, double, double weight, const MAL_MATRIX &, double, const MAL_VECTOR &, double) [protected]
Scaled product .
References MAL_RET_A_by_B.
void GeneratorVelRef::compute_term (MAL_MATRIX &, double, const MAL_MATRIX &, double, const MAL_MATRIX &, double) [protected]
Scaled product.
References MAL_RET_A_by_B.
void GeneratorVelRef::compute_term (MAL_MATRIX &, double, double weight, const MAL_MATRIX &, double, const MAL_MATRIX &, double) [protected]
Scaled product.
References MAL_RET_A_by_B.
Referenced by build_constraints_cop(), build_constraints_feet(), build_invariant_part(), and update_problem().
void GeneratorVelRef::generate_selection_matrices (const std::deque< support_state_t > & deqSupportStates) [protected]
Compute the selection matrices.
Parameters:
[in] deqSupportStates
References Matrices_, PatternGeneratorJRL::MPCTrajectoryGeneration::N_, PatternGeneratorJRL::IntermedQPMat::State(), PatternGeneratorJRL::IntermedQPMat::state_variant_s::V, PatternGeneratorJRL::IntermedQPMat::state_variant_s::V_f, PatternGeneratorJRL::IntermedQPMat::state_variant_s::Vc, PatternGeneratorJRL::IntermedQPMat::state_variant_s::Vc_f, and PatternGeneratorJRL::IntermedQPMat::state_variant_s::VT.
Referenced by preview_support_states().
void GeneratorVelRef::initialize_matrices (linear_inequality_t & Inequalities) [protected]
Initialize inequality matrices.
Parameters:
[in] Objective
References PatternGeneratorJRL::IntermedQPMat::INEQ_COP, and PatternGeneratorJRL::MPCTrajectoryGeneration::N_.
void GeneratorVelRef::initialize_matrices (IntermedQPMat::dynamics_t & Objective) [protected]
Initialize intermediate matrices.
Parameters:
[in] Objective
References PatternGeneratorJRL::MPCTrajectoryGeneration::CoMHeight_, PatternGeneratorJRL::IntermedQPMat::COP, PatternGeneratorJRL::IntermedQPMat::JERK, PatternGeneratorJRL::MPCTrajectoryGeneration::N_, PatternGeneratorJRL::IntermedQPMat::dynamics_s::S, PatternGeneratorJRL::MPCTrajectoryGeneration::T_Prw_, PatternGeneratorJRL::IntermedQPMat::dynamics_s::type, PatternGeneratorJRL::IntermedQPMat::dynamics_s::U, PatternGeneratorJRL::IntermedQPMat::dynamics_s::UT, and PatternGeneratorJRL::IntermedQPMat::VELOCITY.
void GeneratorVelRef::initialize_matrices ()
Initialize intermediate matrices.
References PatternGeneratorJRL::IntermedQPMat::COP, PatternGeneratorJRL::IntermedQPMat::Dynamics(), PatternGeneratorJRL::IntermedQPMat::INEQ_COP, PatternGeneratorJRL::IntermedQPMat::Inequalities(), PatternGeneratorJRL::IntermedQPMat::JERK, Matrices_, and PatternGeneratorJRL::IntermedQPMat::VELOCITY.
void GeneratorVelRef::Ponderation (double weight, int objective)
Set the weights on an objective term.
Parameters:
[in] weight
[in] objective
References Matrices_, PatternGeneratorJRL::IntermedQPMat::Objective(), and PatternGeneratorJRL::IntermedQPMat::objective_variant_s::weight.
void GeneratorVelRef::preview_support_states (const SupportFSM * FSM, std::deque< support_state_t > & deqSupportStates)
Preview support state for the whole preview period.
Parameters:
[in] FSM
[out] deqSupportStates
References PatternGeneratorJRL::MPCTrajectoryGeneration::CurrentTime_, generate_selection_matrices(), Matrices_, PatternGeneratorJRL::MPCTrajectoryGeneration::N_, PatternGeneratorJRL::IntermedQPMat::Reference(), and PatternGeneratorJRL::IntermedQPMat::SupportState().
void PatternGeneratorJRL::GeneratorVelRef::Reference (const reference_t & Ref) [inline]
Inline accessors
References Matrices_, and PatternGeneratorJRL::IntermedQPMat::Reference().
void PatternGeneratorJRL::GeneratorVelRef::SupportState (const support_state_t & SupportState) [inline]
References Matrices_, and PatternGeneratorJRL::IntermedQPMat::SupportState().
void GeneratorVelRef::update_problem (QPProblem & Pb, const std::deque< support_state_t > & SupportStates_deq)
Compute the objective matrices.
Parameters:
[in] Pb
[in] deqSupportStates
References PatternGeneratorJRL::QPProblem_s::add_term(), PatternGeneratorJRL::QPProblem_s::clear(), PatternGeneratorJRL::IntermedQPMat::state_variant_s::CoM, compute_term(), PatternGeneratorJRL::IntermedQPMat::COP_CENTERING, PatternGeneratorJRL::IntermedQPMat::objective_variant_s::dyn, PatternGeneratorJRL::IntermedQPMat::INSTANT_VELOCITY, MAL_MATRIX, MAL_VECTOR, Matrices_, PatternGeneratorJRL::QPProblem_s::MATRIX_Q, PatternGeneratorJRL::MPCTrajectoryGeneration::N_, PatternGeneratorJRL::IntermedQPMat::Objective(), PatternGeneratorJRL::IntermedQPMat::state_variant_s::Ref, PatternGeneratorJRL::IntermedQPMat::State(), PatternGeneratorJRL::IntermedQPMat::state_variant_s::SupportState, PatternGeneratorJRL::IntermedQPMat::state_variant_s::V, PatternGeneratorJRL::IntermedQPMat::state_variant_s::Vc, PatternGeneratorJRL::QPProblem_s::VECTOR_D, PatternGeneratorJRL::IntermedQPMat::state_variant_s::VT, and PatternGeneratorJRL::IntermedQPMat::objective_variant_s::weight.
Member Data Documentation
IntermedQPMat PatternGeneratorJRL::GeneratorVelRef::Matrices_ [protected]
Referenced by build_constraints(), build_invariant_part(), CoM(), compute_global_reference(), generate_selection_matrices(), GeneratorVelRef(), initialize_matrices(), Ponderation(), preview_support_states(), Reference(), SupportState(), and update_problem().