jrl-walkgen: PatternGeneratorJRL::ComputeConvexHull Class Reference
PatternGeneratorJRL::ComputeConvexHull Class Reference
#include </home/buildbot/devel-src/tools/pkg-dev-mng/Testing/Buildbot/slaves/jrlserver/jrlserverubuntu/build-jrl-walkgen-jrlmt-master/pkgsrc/src/Mathematics/ConvexHull.hh>
Public Member Functions
ComputeConvexHull ()
~ComputeConvexHull ()
void DoComputeConvexHull (std::vector< CH_Point > aVecOfPoints, std::vector< CH_Point > &TheConvexHull)
Detailed Description
This class compute the convex hull in 2D.
Constructor & Destructor Documentation
PatternGeneratorJRL::ComputeConvexHull::ComputeConvexHull ()
PatternGeneratorJRL::ComputeConvexHull::~ComputeConvexHull ()
Member Function Documentation
void PatternGeneratorJRL::ComputeConvexHull::DoComputeConvexHull (std::vector< CH_Point > aVecOfPoints, std::vector< CH_Point > & TheConvexHull)
Compute the convex hull by applying Graham's algorithm.
Parameters:
aVecOfPoints,: The set of 2D points on which the convex hull is computed.
TheConvexHull,: The set of 2D points which give the convex hull.
References PatternGeneratorJRL::CH_Point::col, PatternGeneratorJRL::CompareCBRep(), PatternGeneratorJRL::DistanceCHRep(), PatternGeneratorJRL::HRP2CIO_GlobalP0, and PatternGeneratorJRL::CH_Point::row.
Referenced by PatternGeneratorJRL::FootConstraintsAsLinearSystem::BuildLinearConstraintInequalities().