jrl-walkgen: PatternGeneratorJRL::GeneratorVelRef Class Reference
PatternGeneratorJRL::GeneratorVelRef Class Reference
#include </home/buildbot/devel-src/tools/pkg-dev-mng/Testing/Buildbot/slaves/jrlserver/jrlserverubuntu/build-jrl-walkgen-jrlmt-master/pkgsrc/src/ZMPRefTrajectoryGeneration/generator-vel-ref.hh>
Public Member Functions
void setPonderation (IntermedQPMat &Matrices, double weight, int objective)
Set the weights on the objective terms.
void previewSupportStates (IntermedQPMat &Matrices, SupportFSM *FSM, std::deque< support_state_t > &deqSupportStates)
Preview support state for the whole preview period.
void generateSelectionMatrices (IntermedQPMat &Matrices, std::deque< support_state_t > &deqSupportStates)
Compute the selection matrices.
void computeGlobalReference (IntermedQPMat &Matrices, COMState &TrunkStateT)
Set the global reference from the local one and the orientation of the trunk frame for the whole preview window.
void initialize (IntermedQPMat &Matrices)
Initialize the optimization programm.
void buildInequalitiesCoP (linear_inequality_t &Inequalities, FootConstraintsAsLinearSystemForVelRef *FCALS, std::deque< FootAbsolutePosition > &AbsoluteLeftFootPositions, std::deque< FootAbsolutePosition > &AbsoluteRightFootPositions, std::deque< support_state_t > &deqSupportStates, std::deque< double > &PreviewedSupportAngles)
Generate a queue of inequalities with respect to the centers of the feet.
void buildInequalitiesFeet (linear_inequality_t &Inequalities, FootConstraintsAsLinearSystemForVelRef *FCALS, std::deque< FootAbsolutePosition > &AbsoluteLeftFootPositions, std::deque< FootAbsolutePosition > &AbsoluteRightFootPositions, std::deque< support_state_t > &deqSupportStates, std::deque< double > &PreviewedSupportAngles)
Generate a queue of inequality constraints on the feet positions with respect to previous footpositions.
void buildConstraintsCoP (linear_inequality_t &IneqCoP, IntermedQPMat::dynamics_t CoP, IntermedQPMat::state_variant_t &State, int NbStepsPreviewed, QPProblem &Pb)
void buildConstraintsFeet (linear_inequality_t &IneqFeet, IntermedQPMat::state_variant_t &State, int NbStepsPreviewed, QPProblem &Pb)
void buildConstraints (IntermedQPMat &Matrices, QPProblem &Pb, FootConstraintsAsLinearSystemForVelRef *FCALS, std::deque< FootAbsolutePosition > &AbsoluteLeftFootPositions, std::deque< FootAbsolutePosition > &AbsoluteRightFootPositions, std::deque< support_state_t > &deqSupportStates, std::deque< double > &PreviewedSupportAngles)
void buildInvariantPart (QPProblem &Pb, IntermedQPMat &Matrices)
Build the constant part of the objective.
void updateProblem (QPProblem &Pb, IntermedQPMat &Matrices, std::deque< support_state_t > &deqSupportStates)
Compute the objective matrices.
Constructors and destructors.
GeneratorVelRef (SimplePluginManager *lSPM)
~GeneratorVelRef ()
Constructor & Destructor Documentation
GeneratorVelRef::GeneratorVelRef (SimplePluginManager * lSPM)
GeneratorVelRef::~GeneratorVelRef ()
Member Function Documentation
void GeneratorVelRef::buildConstraints (IntermedQPMat & Matrices, QPProblem & Pb, FootConstraintsAsLinearSystemForVelRef * FCALS, std::deque< FootAbsolutePosition > & AbsoluteLeftFootPositions, std::deque< FootAbsolutePosition > & AbsoluteRightFootPositions, std::deque< support_state_t > & deqSupportStates, std::deque< double > & PreviewedSupportAngles)
References buildConstraintsCoP(), buildConstraintsFeet(), buildInequalitiesCoP(), buildInequalitiesFeet(), PatternGeneratorJRL::IntermedQPMat::COP, PatternGeneratorJRL::IntermedQPMat::Dynamics(), PatternGeneratorJRL::IntermedQPMat::INEQ_COP, PatternGeneratorJRL::IntermedQPMat::INEQ_FEET, PatternGeneratorJRL::IntermedQPMat::Inequalities(), and PatternGeneratorJRL::IntermedQPMat::State().
void GeneratorVelRef::buildConstraintsCoP (linear_inequality_t & IneqCoP, IntermedQPMat::dynamics_t CoP, IntermedQPMat::state_variant_t & State, int NbStepsPreviewed, QPProblem & Pb)
References PatternGeneratorJRL::QPProblem_s::addTerm(), PatternGeneratorJRL::IntermedQPMat::state_variant_s::CoM, PatternGeneratorJRL::QPProblem_s::MATRIX_DU, PatternGeneratorJRL::IntermedQPMat::dynamics_s::S, PatternGeneratorJRL::IntermedQPMat::state_variant_s::SupportFoot, PatternGeneratorJRL::IntermedQPMat::dynamics_s::U, PatternGeneratorJRL::IntermedQPMat::state_variant_s::V, PatternGeneratorJRL::IntermedQPMat::state_variant_s::Vc, and PatternGeneratorJRL::QPProblem_s::VECTOR_DS.
Referenced by buildConstraints().
void GeneratorVelRef::buildConstraintsFeet (linear_inequality_t & IneqFeet, IntermedQPMat::state_variant_t & State, int NbStepsPreviewed, QPProblem & Pb)
References PatternGeneratorJRL::QPProblem_s::addTerm(), PatternGeneratorJRL::QPProblem_s::MATRIX_DU, PatternGeneratorJRL::IntermedQPMat::state_variant_s::SupportFoot, PatternGeneratorJRL::IntermedQPMat::state_variant_s::V_f, PatternGeneratorJRL::IntermedQPMat::state_variant_s::Vc_f, and PatternGeneratorJRL::QPProblem_s::VECTOR_DS.
Referenced by buildConstraints().
void GeneratorVelRef::buildInequalitiesCoP (linear_inequality_t & Inequalities, FootConstraintsAsLinearSystemForVelRef * FCALS, std::deque< FootAbsolutePosition > & AbsoluteLeftFootPositions, std::deque< FootAbsolutePosition > & AbsoluteRightFootPositions, std::deque< support_state_t > & deqSupportStates, std::deque< double > & PreviewedSupportAngles)
Generate a queue of inequalities with respect to the centers of the feet.
Parameters:
[out] Inequalities
[in] FCALS
[in] AbsoluteLeftFootPositions
[in] AbsoluteRightFootPositions
[in] deqSupportStates
[in] PreviewedSupportAngles
Referenced by buildConstraints().
void GeneratorVelRef::buildInequalitiesFeet (linear_inequality_t & Inequalities, FootConstraintsAsLinearSystemForVelRef * FCALS, std::deque< FootAbsolutePosition > & AbsoluteLeftFootPositions, std::deque< FootAbsolutePosition > & AbsoluteRightFootPositions, std::deque< support_state_t > & deqSupportStates, std::deque< double > & PreviewedSupportAngles)
Generate a queue of inequality constraints on the feet positions with respect to previous footpositions.
Parameters:
[out] Inequalities
[in] FCALS
[in] AbsoluteLeftFootPositions
[in] AbsoluteRightFootPositions
[in] deqSupportStates
[in] PreviewedSupportAngles
Referenced by buildConstraints().
void GeneratorVelRef::buildInvariantPart (QPProblem & Pb, IntermedQPMat & Matrices)
Build the constant part of the objective.
Parameters:
[in] Pb
[in] Matrices
References PatternGeneratorJRL::QPProblem_s::addTerm(), PatternGeneratorJRL::IntermedQPMat::COP_CENTERING, PatternGeneratorJRL::IntermedQPMat::objective_variant_s::dyn, PatternGeneratorJRL::IntermedQPMat::INSTANT_VELOCITY, PatternGeneratorJRL::IntermedQPMat::JERK_MIN, PatternGeneratorJRL::QPProblem_s::MATRIX_Q, PatternGeneratorJRL::IntermedQPMat::Objective(), and PatternGeneratorJRL::IntermedQPMat::objective_variant_s::weight.
void GeneratorVelRef::computeGlobalReference (IntermedQPMat & Matrices, COMState & TrunkStateT)
Set the global reference from the local one and the orientation of the trunk frame for the whole preview window.
Parameters:
[in] Matrices
[in] TrunkStateT State of the trunk at the end of the acceleration phase
References PatternGeneratorJRL::MPCTrajectoryGeneration::m_N, PatternGeneratorJRL::MPCTrajectoryGeneration::m_T_Prw, MAL_VECTOR_RESIZE, PatternGeneratorJRL::IntermedQPMat::Reference(), and PatternGeneratorJRL::COMState_s::yaw.
void GeneratorVelRef::generateSelectionMatrices (IntermedQPMat & Matrices, std::deque< support_state_t > & deqSupportStates)
Compute the selection matrices.
Parameters:
[in] Matrices
[in] deqSupportStates
References PatternGeneratorJRL::MPCTrajectoryGeneration::m_N, PatternGeneratorJRL::IntermedQPMat::State(), PatternGeneratorJRL::IntermedQPMat::state_variant_s::V, PatternGeneratorJRL::IntermedQPMat::state_variant_s::V_f, PatternGeneratorJRL::IntermedQPMat::state_variant_s::Vc, PatternGeneratorJRL::IntermedQPMat::state_variant_s::Vc_f, and PatternGeneratorJRL::IntermedQPMat::state_variant_s::VT.
Referenced by previewSupportStates().
void GeneratorVelRef::initialize (IntermedQPMat & Matrices)
Initialize the optimization programm.
Parameters:
[in] Pb
[in] Matrices
References PatternGeneratorJRL::IntermedQPMat::COP, PatternGeneratorJRL::IntermedQPMat::Dynamics(), PatternGeneratorJRL::IntermedQPMat::INEQ_COP, PatternGeneratorJRL::IntermedQPMat::Inequalities(), PatternGeneratorJRL::IntermedQPMat::JERK, and PatternGeneratorJRL::IntermedQPMat::VELOCITY.
void GeneratorVelRef::previewSupportStates (IntermedQPMat & Matrices, SupportFSM * FSM, std::deque< support_state_t > & deqSupportStates)
Preview support state for the whole preview period.
Parameters:
[in] Matrices
[in] FSM
[out] deqSupportStates
References generateSelectionMatrices(), PatternGeneratorJRL::MPCTrajectoryGeneration::m_CurrentTime, PatternGeneratorJRL::MPCTrajectoryGeneration::m_N, and PatternGeneratorJRL::IntermedQPMat::Reference().
void GeneratorVelRef::setPonderation (IntermedQPMat & Matrices, double weight, int objective)
Set the weights on the objective terms.
Parameters:
[out] Matrices
[in] weight
[in] objective
References PatternGeneratorJRL::IntermedQPMat::Objective(), and PatternGeneratorJRL::IntermedQPMat::objective_variant_s::weight.
void GeneratorVelRef::updateProblem (QPProblem & Pb, IntermedQPMat & Matrices, std::deque< support_state_t > & deqSupportStates)
Compute the objective matrices.
Parameters:
[in] Pb
[in] Matrices
[in] deqSupportStates
References PatternGeneratorJRL::QPProblem_s::addTerm(), PatternGeneratorJRL::QPProblem_s::clear(), PatternGeneratorJRL::IntermedQPMat::state_variant_s::CoM, PatternGeneratorJRL::IntermedQPMat::COP_CENTERING, PatternGeneratorJRL::IntermedQPMat::objective_variant_s::dyn, PatternGeneratorJRL::IntermedQPMat::INSTANT_VELOCITY, MAL_MATRIX, PatternGeneratorJRL::QPProblem_s::MATRIX_Q, PatternGeneratorJRL::IntermedQPMat::Objective(), PatternGeneratorJRL::IntermedQPMat::state_variant_s::Ref, PatternGeneratorJRL::IntermedQPMat::State(), PatternGeneratorJRL::IntermedQPMat::state_variant_s::SupportFoot, PatternGeneratorJRL::IntermedQPMat::state_variant_s::V, PatternGeneratorJRL::IntermedQPMat::state_variant_s::Vc, PatternGeneratorJRL::QPProblem_s::VECTOR_D, PatternGeneratorJRL::IntermedQPMat::state_variant_s::VT, and PatternGeneratorJRL::IntermedQPMat::objective_variant_s::weight.