var hierarchy =
[
    [ "alist", "a00011.html", null ],
    [ "PatternGeneratorJRL::AnalyticalZMPCOGTrajectory", "a00012.html", null ],
    [ "PatternGeneratorJRL::CH_Point", "a00013.html", null ],
    [ "cilist", "a00014.html", null ],
    [ "cllist", "a00015.html", null ],
    [ "complex", "a00016.html", null ],
    [ "PatternGeneratorJRL::COMPosition_s", "a00017.html", null ],
    [ "PatternGeneratorJRL::ComputeConvexHull", "a00018.html", null ],
    [ "PatternGeneratorJRL::COMState_s", "a00019.html", null ],
    [ "doublecomplex", "a00020.html", null ],
    [ "PatternGeneratorJRL::FootAbsolutePosition_t", "a00021.html", null ],
    [ "PatternGeneratorJRL::FootConstraintsAsLinearSystem", "a00022.html", null ],
    [ "PatternGeneratorJRL::FootConstraintsAsLinearSystemForVelRef", "a00023.html", null ],
    [ "PatternGeneratorJRL::FootHalfSize", "a00024.html", null ],
    [ "icilist", "a00025.html", null ],
    [ "inlist", "a00026.html", null ],
    [ "PatternGeneratorJRL::LinearConstraintInequality_s", "a00027.html", null ],
    [ "PatternGeneratorJRL::LinearConstraintInequalityFreeFeet_s", "a00028.html", null ],
    [ "PatternGeneratorJRL::LinearizedInvertedPendulum2D", "a00029.html", null ],
    [ "PatternGeneratorJRL::ltCH_Point", "a00030.html", null ],
    [ "Multitype", "a00031.html", null ],
    [ "Namelist", "a00032.html", null ],
    [ "olist", "a00033.html", null ],
    [ "PatternGeneratorJRL::OptimalControllerSolver", "a00034.html", null ],
    [ "PatternGeneratorJRL::PatternGeneratorInterface", "a00035.html", null ],
    [ "Optimization::Solver::PLDPSolver", "a00036.html", null ],
    [ "Optimization::Solver::PLDPSolverHerdt", "a00037.html", null ],
    [ "PatternGeneratorJRL::Polynome", "a00038.html", [
      [ "PatternGeneratorJRL::Polynome3", "a00039.html", null ],
      [ "PatternGeneratorJRL::Polynome4", "a00040.html", null ],
      [ "PatternGeneratorJRL::Polynome5", "a00041.html", null ],
      [ "PatternGeneratorJRL::Polynome6", "a00042.html", null ],
      [ "PatternGeneratorJRL::StepOverPolynomeFoot", "a00047.html", null ],
      [ "PatternGeneratorJRL::StepOverPolynomeFootXtoTime", "a00048.html", null ],
      [ "PatternGeneratorJRL::StepOverPolynomeFootZtoX", "a00049.html", null ],
      [ "PatternGeneratorJRL::StepOverPolynomeHip4", "a00050.html", null ]
    ] ],
    [ "PatternGeneratorJRL::PreviewControl", "a00043.html", null ],
    [ "PatternGeneratorJRL::ReferenceAbsoluteVelocity_t", "a00044.html", null ],
    [ "PatternGeneratorJRL::RelativeFootPosition_s", "a00045.html", null ],
    [ "PatternGeneratorJRL::StepOverClampedCubicSpline", "a00046.html", null ],
    [ "PatternGeneratorJRL::StepOverSpline", "a00051.html", null ],
    [ "PatternGeneratorJRL::SupportFeet_s", "a00052.html", null ],
    [ "PatternGeneratorJRL::SupportFSM", "a00053.html", null ],
    [ "t_cmache_", "a00054.html", null ],
    [ "Vardesc", "a00055.html", null ],
    [ "PatternGeneratorJRL::ZMPPosition_s", "a00056.html", null ],
    [ "PatternGeneratorJRL::ZMPPreviewControlWithMultiBodyZMP", "a00057.html", null ]
];